### ISSUE TITLE
unable to locate the intended deleted tweet

### ISSUE THREAD

**Issue by ierothas** [ayanamists/oh-my-old-tweet#3]
hi!! appreciate you a lot for the tool. however, i was unable to locate the deleted tweet for which i was searching. could you perhaps help me with this matter?

i've tried searching using the tweet ID (which i had saved prior to deletion), but i was still unable to locate it in omot

**Comment by ayanamists** [comment]
Unfortunately, OMOT does not currently support searching tweets based on tweet id. If you really need this feature, I can consider implementing it. However, in the meantime, you can try searching for the tweet directly on archive.org using the following URL scheme:

```
https://web.archive.org/web/*/https://twitter.com/{user_name}/status/{tweet_id}
```

E.g. `https://web.archive.org/web/*/https://twitter.com/_iori_n/status/523389174242488320`. Note archive.org may **not** archive your targeted tweet, in this case you cannot find it in archive.org or omot.

Hope archive.org has archived your targeted tweet! And also, you can try [gallery-dl](https://github.com/mikf/gallery-dl) to save the tweet in your disk before they're deleted.
